spring:
  application:
    name: product-service
  profiles:
    active: localhost
  main:
      allow-bean-definition-overriding: true
info:
  component: Product Service

---
spring:
  config:
    activate:
      on-profile: localhost
  cloud:
    config:
      uri: http://localhost:8888
  jpa:
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.MySQLDialect
      default-schema: stock_management
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/stock_management?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/stock_management?useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 1234

server:
  port: 9788

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

---
spring:
  config:
    activate:
      on-profile: stage
  jpa:
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.MySQLDialect
      default-schema: stock_management
    show-sql: true
  datasource:
    url: jdbc:mysql://root:3306/stock_management?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    instance-id: ${spring.application.name}:${random.uuid}