version: '3.3'

services:
  zuul-edge-server:
    hostname: zuul-edge-server
    image: api-gateway-server:0.0.1
    networks:
      - stock-management-network-backend
    expose:
      - 8762
    ports:
      - 8762:8762
    environment:
      - "SPRING_PROFILES_ACTIVE=stage"
    entrypoint: ["java","-jar","app.jar"]

networks:
  stock-management-network-backend: